branches:
  only:
  - master
addons:
  ssh_known_hosts:
    - worldcubeassociation.org
    - staging.worldcubeassociation.org
before_install:
  # Decrypt the RSA key file.
  - openssl aes-256-cbc -K $encrypted_d2c91d5e690a_key -iv $encrypted_d2c91d5e690a_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - sudo bin/install_dependencies.sh
script: bin/build.sh
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    target_branch: build
  - provider: script
    skip_cleanup: true
    script: bin/deploy.sh
